"""empty message

Revision ID: 15889763fcfe
Revises: 81268086361e
Create Date: 2023-08-19 02:18:22.077159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15889763fcfe'
down_revision = '81268086361e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_wash', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=500), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('salt')
        batch_op.drop_column('password_wash')

    # ### end Alembic commands ###
